import { Arsenal } from '@/types';

export const defaultArsenal: Arsenal = {
  camera: {
    label: 'Camera Angles',
    icon: '◇',
    stateKey: 'angle',
    cards: [
      { id: 'low', label: 'Low Angle', value: 'Low Angle', desc: 'Power & dominance' },
      { id: 'high', label: 'High Angle', value: 'High Angle', desc: 'Vulnerability' },
      { id: 'dutch', label: 'Dutch Angle', value: 'Dutch Angle', desc: 'Tension & unease' },
      { id: 'eye', label: 'Eye Level', value: 'Eye Level', desc: 'Neutral & intimate' },
      { id: 'birds', label: "Bird's Eye", value: "Bird's Eye View", desc: 'Godlike perspective' },
      { id: 'worms', label: "Worm's Eye", value: "Worm's Eye View", desc: 'Extreme drama' },
      { id: 'over', label: 'Over Shoulder', value: 'Over-the-Shoulder', desc: 'POV intimacy' },
      { id: 'pov', label: 'POV Shot', value: 'POV Shot', desc: 'First person' },
    ],
  },
  movement: {
    label: 'Camera Movement',
    icon: '↗',
    stateKey: 'movement',
    cards: [
      { id: 'push', label: 'Push In', value: 'Push In', desc: 'Building intensity' },
      { id: 'pull', label: 'Pull Out', value: 'Pull Out', desc: 'Revealing context' },
      { id: 'dolly', label: 'Dolly Shot', value: 'Dolly Shot', desc: 'Smooth tracking' },
      { id: 'crane', label: 'Crane Shot', value: 'Crane Shot', desc: 'Sweeping motion' },
      { id: 'orbit', label: 'Orbit', value: 'Orbital Shot', desc: '360° revolution' },
      { id: 'whip', label: 'Whip Pan', value: 'Whip Pan', desc: 'Rapid transition' },
      { id: 'handheld', label: 'Handheld', value: 'Handheld', desc: 'Raw & visceral' },
      { id: 'steadicam', label: 'Steadicam', value: 'Steadicam Shot', desc: 'Floating stability' },
    ],
  },
  lens: {
    label: 'Lens & Optics',
    icon: '◉',
    stateKey: 'lens',
    cards: [
      { id: '14mm', label: '14mm Ultra Wide', value: '14mm ultra-wide lens', desc: 'Extreme distortion' },
      { id: '24mm', label: '24mm Wide', value: '24mm wide lens', desc: 'Environmental' },
      { id: '35mm', label: '35mm', value: '35mm lens', desc: 'Cinematic standard' },
      { id: '50mm', label: '50mm', value: '50mm lens', desc: 'Natural eye' },
      { id: '85mm', label: '85mm Portrait', value: '85mm portrait lens', desc: 'Compression beauty' },
      { id: '135mm', label: '135mm Telephoto', value: '135mm telephoto', desc: 'Isolated focus' },
      { id: 'macro', label: 'Macro', value: 'Macro lens', desc: 'Extreme detail' },
      { id: 'anamorphic', label: 'Anamorphic', value: 'Anamorphic lens', desc: 'Cinematic flares' },
    ],
  },
  lighting: {
    label: 'Lighting',
    icon: '☀',
    stateKey: 'lighting',
    cards: [
      { id: 'golden', label: 'Golden Hour', value: 'Golden hour lighting', desc: 'Warm magic' },
      { id: 'blue', label: 'Blue Hour', value: 'Blue hour lighting', desc: 'Cool mystery' },
      { id: 'neon', label: 'Neon Noir', value: 'Neon noir lighting', desc: 'Cyberpunk glow' },
      { id: 'rim', label: 'Rim Light', value: 'Dramatic rim lighting', desc: 'Edge definition' },
      { id: 'chiaroscuro', label: 'Chiaroscuro', value: 'Chiaroscuro lighting', desc: 'Renaissance drama' },
      { id: 'volumetric', label: 'Volumetric', value: 'Volumetric god rays', desc: 'Ethereal beams' },
      { id: 'practical', label: 'Practical', value: 'Practical lighting', desc: 'In-scene sources' },
      { id: 'silhouette', label: 'Silhouette', value: 'Silhouette backlight', desc: 'Mystery shape' },
    ],
  },
  style: {
    label: 'Visual Style',
    icon: '◈',
    stateKey: 'style',
    cards: [
      { id: 'cinematic', label: 'Cinematic', value: 'Cinematic', desc: 'Film production' },
      { id: 'hyperreal', label: 'Hyperrealistic', value: 'Hyperrealistic', desc: '8K photorealism' },
      { id: 'noir', label: 'Film Noir', value: 'Film Noir style', desc: 'Shadow & mystery' },
      { id: 'scifi', label: 'Sci-Fi Epic', value: 'Epic sci-fi', desc: 'Future worlds' },
      { id: 'anime', label: 'Anime Cinematic', value: 'Anime cinematic', desc: 'Japanese animation' },
      { id: 'fantasy', label: 'Dark Fantasy', value: 'Dark fantasy', desc: 'Gothic wonder' },
      { id: 'documentary', label: 'Documentary', value: 'Documentary style', desc: 'Raw authenticity' },
      { id: 'retro', label: 'Retro Film', value: 'Retro 70s film', desc: 'Vintage aesthetic' },
    ],
  },
  filmStock: {
    label: 'Film Stock',
    icon: '▣',
    stateKey: 'filmStock',
    cards: [
      { id: 'kodak5219', label: 'Kodak Vision3 500T', value: 'Kodak Vision3 500T', desc: 'Hollywood standard' },
      { id: 'kodak5207', label: 'Kodak Vision3 250D', value: 'Kodak Vision3 250D', desc: 'Daylight master' },
      { id: 'fuji', label: 'Fujifilm Eterna', value: 'Fujifilm Eterna', desc: 'Soft elegance' },
      { id: 'portra', label: 'Kodak Portra 400', value: 'Kodak Portra 400', desc: 'Portrait beauty' },
      { id: 'ektar', label: 'Kodak Ektar 100', value: 'Kodak Ektar 100', desc: 'Vivid saturation' },
      { id: 'cinestill', label: 'CineStill 800T', value: 'CineStill 800T', desc: 'Neon halation' },
      { id: 'ilford', label: 'Ilford HP5', value: 'Ilford HP5 B&W', desc: 'Classic monochrome' },
      { id: 'trix', label: 'Kodak Tri-X', value: 'Kodak Tri-X 400', desc: 'Gritty contrast' },
    ],
  },
};
