import { Preset } from '@/types';

export const defaultPresets: Preset[] = [
  {
    id: 'epic-hero',
    name: 'Epic Hero Shot',
    icon: '⚔',
    description: 'Low angle power stance with dramatic rim lighting',
    color: '#ff6b35',
    config: {
      angle: 'Low Angle',
      movement: 'Push In',
      lens: 'Anamorphic lens',
      lighting: 'Dramatic rim lighting',
      style: 'Cinematic',
      filmStock: 'Kodak Vision3 500T',
      aspectRatio: '21:9',
    },
  },
  {
    id: 'intimate-doc',
    name: 'Intimate Documentary',
    icon: '◎',
    description: 'Handheld eye-level with natural practical lighting',
    color: '#10b981',
    config: {
      angle: 'Eye Level',
      movement: 'Handheld',
      lens: '35mm lens',
      lighting: 'Practical lighting',
      style: 'Documentary style',
      filmStock: 'Kodak Portra 400',
      aspectRatio: '16:9',
    },
  },
  {
    id: 'cyberpunk-chase',
    name: 'Cyberpunk Chase',
    icon: '↗',
    description: 'Dutch angle whip pan with neon noir aesthetics',
    color: '#8b5cf6',
    config: {
      angle: 'Dutch Angle',
      movement: 'Whip Pan',
      lens: '24mm wide lens',
      lighting: 'Neon noir lighting',
      style: 'Epic sci-fi',
      filmStock: 'CineStill 800T',
      aspectRatio: '21:9',
    },
  },
  {
    id: 'noir-mystery',
    name: 'Film Noir Mystery',
    icon: '◐',
    description: 'High contrast shadows with venetian blind lighting',
    color: '#64748b',
    config: {
      angle: 'High Angle',
      movement: 'Dolly Shot',
      lens: '50mm lens',
      lighting: 'Chiaroscuro lighting',
      style: 'Film Noir style',
      filmStock: 'Ilford HP5 B&W',
      aspectRatio: '16:9',
    },
  },
  {
    id: 'dreamlike-fantasy',
    name: 'Dreamlike Fantasy',
    icon: '✧',
    description: 'Ethereal crane shot with volumetric god rays',
    color: '#a855f7',
    config: {
      angle: "Bird's Eye View",
      movement: 'Crane Shot',
      lens: '85mm portrait lens',
      lighting: 'Volumetric god rays',
      style: 'Dark fantasy',
      filmStock: 'Fujifilm Eterna',
      aspectRatio: '16:9',
    },
  },
  {
    id: 'action-sequence',
    name: 'Action Sequence',
    icon: '⚡',
    description: 'Dynamic steadicam with motion blur emphasis',
    color: '#ef4444',
    config: {
      angle: 'Low Angle',
      movement: 'Steadicam Shot',
      lens: '14mm ultra-wide lens',
      lighting: 'Dramatic rim lighting',
      style: 'Cinematic',
      filmStock: 'Kodak Vision3 500T',
      aspectRatio: '21:9',
    },
  },
  {
    id: 'horror-tension',
    name: 'Horror Tension',
    icon: '◈',
    description: 'Slow push-in with deep shadows and isolation',
    color: '#1e293b',
    config: {
      angle: "Worm's Eye View",
      movement: 'Push In',
      lens: '24mm wide lens',
      lighting: 'Silhouette backlight',
      style: 'Dark fantasy',
      filmStock: 'Kodak Tri-X 400',
      aspectRatio: '16:9',
    },
  },
  {
    id: 'romantic-golden',
    name: 'Romantic Golden Hour',
    icon: '☀',
    description: 'Soft telephoto compression with warm backlight',
    color: '#f59e0b',
    config: {
      angle: 'Eye Level',
      movement: 'Orbital Shot',
      lens: '135mm telephoto',
      lighting: 'Golden hour lighting',
      style: 'Cinematic',
      filmStock: 'Kodak Portra 400',
      aspectRatio: '16:9',
    },
  },
  {
    id: 'anime-epic',
    name: 'Anime Cinematic',
    icon: '◇',
    description: 'Dynamic angles with stylized lighting',
    color: '#ec4899',
    config: {
      angle: 'Low Angle',
      movement: 'Push In',
      lens: '35mm lens',
      lighting: 'Dramatic rim lighting',
      style: 'Anime cinematic',
      filmStock: null,
      aspectRatio: '16:9',
    },
  },
  {
    id: 'vintage-retro',
    name: 'Vintage 70s Film',
    icon: '◔',
    description: 'Soft focus with grain and warm color cast',
    color: '#d97706',
    config: {
      angle: 'Eye Level',
      movement: 'Dolly Shot',
      lens: '50mm lens',
      lighting: 'Practical lighting',
      style: 'Retro 70s film',
      filmStock: 'Kodak Ektar 100',
      aspectRatio: '16:9',
    },
  },
  {
    id: 'macro-detail',
    name: 'Extreme Macro',
    icon: '◉',
    description: 'Ultra close-up with shallow depth of field',
    color: '#06b6d4',
    config: {
      angle: 'Eye Level',
      movement: null,
      lens: 'Macro lens',
      lighting: 'Practical lighting',
      style: 'Hyperrealistic',
      filmStock: 'Kodak Vision3 250D',
      aspectRatio: '1:1',
    },
  },
  {
    id: 'surveillance',
    name: 'Surveillance Footage',
    icon: '◫',
    description: 'High angle static shot with harsh lighting',
    color: '#475569',
    config: {
      angle: 'High Angle',
      movement: null,
      lens: '24mm wide lens',
      lighting: 'Practical lighting',
      style: 'Documentary style',
      filmStock: null,
      aspectRatio: '16:9',
    },
  },
];
