import { Platform, PlatformId } from '@/types';

export const platforms: Record<PlatformId, Platform> = {
  midjourney: {
    id: 'midjourney',
    name: 'Midjourney v6',
    shortName: 'MJ',
    icon: '◆',
    color: '#ff6b35',
    type: 'image',
    description: 'Comma-separated with parameters',
  },
  dalle: {
    id: 'dalle',
    name: 'DALL-E 3',
    shortName: 'D3',
    icon: '○',
    color: '#10b981',
    type: 'image',
    description: 'Natural language descriptions',
  },
  ideogram: {
    id: 'ideogram',
    name: 'Ideogram 2.0',
    shortName: 'ID',
    icon: '◐',
    color: '#ec4899',
    type: 'image',
    description: 'Text-aware generation',
  },
  leonardo: {
    id: 'leonardo',
    name: 'Leonardo AI',
    shortName: 'LEO',
    icon: '◇',
    color: '#a855f7',
    type: 'image',
    description: 'Precise control prompts',
  },
  stable: {
    id: 'stable',
    name: 'Stable Diffusion',
    shortName: 'SD',
    icon: '◈',
    color: '#6366f1',
    type: 'image',
    description: 'Weighted token syntax',
  },
  grok: {
    id: 'grok',
    name: 'Grok (Flux.1)',
    shortName: 'GRK',
    icon: '✕',
    color: '#f59e0b',
    type: 'image',
    description: 'Technical precision',
  },
  runway: {
    id: 'runway',
    name: 'Runway Gen-3',
    shortName: 'RW',
    icon: '▸',
    color: '#8b5cf6',
    type: 'video',
    description: 'Movement-first syntax',
  },
  veo: {
    id: 'veo',
    name: 'Google Veo',
    shortName: 'VEO',
    icon: '◎',
    color: '#3b82f6',
    type: 'video',
    description: 'Structured cinematography',
  },
  sora: {
    id: 'sora',
    name: 'OpenAI Sora',
    shortName: 'SRA',
    icon: '◉',
    color: '#14b8a6',
    type: 'video',
    description: 'Cinematic scene description',
  },
  pika: {
    id: 'pika',
    name: 'Pika Labs',
    shortName: 'PIK',
    icon: '▹',
    color: '#f43f5e',
    type: 'video',
    description: 'Motion-focused prompts',
  },
  kling: {
    id: 'kling',
    name: 'Kling AI',
    shortName: 'KLG',
    icon: '◭',
    color: '#22d3ee',
    type: 'video',
    description: 'Dynamic scene control',
  },
};

export const platformList = Object.values(platforms);

export const imagePlatforms = platformList.filter((p) => p.type === 'image');
export const videoPlatforms = platformList.filter((p) => p.type === 'video');
